#!/usr/bin/env python3
"""Generate the board pinmux DTSI from the stock IPL's own pad table.

    gen_pinmux.py --ipl ipl-hbas-dra526-hdisys-nand.bin \
                  [--labels ipl_pad_table_labeled.csv] -o hogtied-boombox-pinmux.dtsi

The IPL writes 155 pad halfwords from a table at body offset 0x4240
(8-byte entries: u32 address, u16 value, u16 pad; function 0x40200CC4).
HogTiedOS boots straight from the IPL, so this is exactly the pad state the
kernel inherits. The DTSI re-applies the same values as pinctrl-single hogs,
which changes nothing at boot but makes the state explicit.

Values come only from the IPL. The optional labels CSV (board/clock/pin
handoff, AM35xx SPRUGR0C names) only adds comments.
"""
import argparse
import csv
import struct
import sys

TABLE_OFF, N_PADS = 0x4240, 155
WRAPPER = 8

# (label, base, size, IOPAD macro) as defined by mainline am3517.dtsi/omap3.dtsi
CONTROLLERS = [
    ('omap3_pmx_core', 0x48002030, 0x238, 'OMAP3_CORE1_IOPAD'),
    ('omap3_pmx_core2', 0x480025D8, 0x24, 'OMAP3430_CORE2_IOPAD'),
    ('omap3_pmx_wkup', 0x48002A00, 0x5C, 'OMAP3_WKUP_IOPAD'),
]
# Pads the labels CSV leaves blank but whose name follows from a labeled neighbour.
EXTRA_LABELS = {0x480021BA: 'i2c1_scl (inferred: pairs with i2c1_sda at 0x21bc)'}


def read_table(ipl_path):
    raw = open(ipl_path, 'rb').read()
    size, load = struct.unpack_from('<II', raw, 0)
    if (size, load) != (0x6000, 0x40200000):
        sys.exit(f'unexpected IPL wrapper {size:#x}/{load:#x}: not the stock IPL?')
    body = raw[WRAPPER:]
    pads = [struct.unpack_from('<IH', body, TABLE_OFF + 8 * i) for i in range(N_PADS)]
    after = struct.unpack_from('<I', body, TABLE_OFF + 8 * N_PADS)[0]
    if after != 0xCC996633:     # the slot-valid magic follows the table
        sys.exit('pad table end marker not found: not the stock IPL?')
    if len({a for a, _ in pads}) != N_PADS:
        sys.exit('duplicate pad addresses in table')
    return pads


def decode(v):
    """Bits per mainline <dt-bindings/pinctrl/omap.h>: [2:0] mux mode,
    3 PULL_ENA, 4 PULL_UP, 8 INPUT_EN, 9+ off-mode/wakeup."""
    pull = ('pull-up' if v & 0x10 else 'pull-down') if v & 0x8 else 'no pull'
    return f'mode {v & 7}, {"input" if v & 0x100 else "input off"}, {pull}' + \
        (', off-mode cfg' if v & 0xFE00 else '')


def load_labels(path):
    labels = dict(EXTRA_LABELS)
    if path:
        for r in csv.DictReader(open(path)):
            a, v = int(r['address'], 16), int(r['value'], 16)
            name, func = r['compatible_pad_name'], r['compatible_selected_function']
            mode = v & 7
            if not name:
                continue
            if func and func != name:
                labels[a] = f'{name} -> {func}'
            elif func:
                labels[a] = name
            else:
                labels[a] = f'{name} (mode {mode} function not labeled)'
    return labels


def render(pads, labels):
    out = ['// SPDX-License-Identifier: GPL-2.0-only',
           '/*',
           ' * GENERATED by tools/pinmux/gen_pinmux.py - do not edit by hand.',
           ' *',
           ' * Board pad configuration = the stock IPL pad table (155 halfword writes,',
           ' * IPL body offset 0x4240, written by 0x40200CC4). HogTiedOS boots directly',
           ' * from the IPL, so these hogs re-apply the state the kernel already has.',
           ' * Names are AM35xx (SPRUGR0C) compatible labels, comments only; they are',
           ' * not proof of DRA526 ball or net names.',
           ' */',
           '#include <dt-bindings/pinctrl/omap.h>',
           '']
    for label, base, size, macro in CONTROLLERS:
        mine = sorted((a, v) for a, v in pads if base <= a < base + size)
        short = label[len('omap3_pmx_'):]          # core / core2 / wkup
        out += [f'&{label} {{',
                '\tstatus = "okay";',
                '\tpinctrl-names = "default";',
                f'\tpinctrl-0 = <&board_{short}_pins>;',
                '',
                f'\tboard_{short}_pins: board-{short}-pins {{',
                '\t\tpinctrl-single,pins = <']
        for a, v in mine:
            name = labels.get(a, 'unlabeled')
            out.append(f'\t\t\t{macro}({a & 0xFFFF:#06x}, {v:#06x})\t/* {name}: {decode(v)} */')
        out += ['\t\t>;', '\t};', '};', '']
    placed = sum(1 for a, _ in pads for _, b, s, _ in CONTROLLERS if b <= a < b + s)
    if placed != N_PADS:
        sys.exit(f'{N_PADS - placed} pads fall outside the known pin controllers')
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--ipl', required=True)
    ap.add_argument('--labels')
    ap.add_argument('-o', '--output', required=True)
    a = ap.parse_args()
    text = render(read_table(a.ipl), load_labels(a.labels))
    open(a.output, 'w').write(text)
    print(f'wrote {a.output}: {N_PADS} pads')


if __name__ == '__main__':
    main()
