#!/usr/bin/env python3
"""Generate the "Harley" EQ preset table for libhbas.

For each factory EQ profile <cfg>_<ON|OFF>.bin (and HS_<ON|OFF>.bin), run
Harley's own tone-stage design (harley_tone.py) with bass/treble flat, at
every volume step, and fit the resulting curve (loudness contour + fixed
voicing, relative to 1 kHz) with the HogTiedOS 7-band EQ. Only those
derived integers go into the repository; Harley's files stay local.

    gen_harley_eq.py AUDIOCTRLSVC EQ_DIR OUT.c
"""
import glob
import math
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'docs', 'findings'))
import eqtool  # noqa: E402
from harley_tone import ToneDesigner  # noqa: E402

FS = 48000.0
BANDS = [63, 160, 400, 1000, 2500, 6300, 16000]     # libhbas hbas_eq_band_hz
Q = 1.05                                            # HBAS_EQ_Q
MAX_DB = 10                                         # HBAS_EQ_MAX_DB
VOL_STEPS = 18                                      # HBAS_VOL_STEPS
GRID = [30 * 2 ** (i / 12) for i in range(0, 12 * 9 + 1)]   # 30 Hz .. ~15 kHz
HEADSET = 256


def biquad_db(b, f):
    b0, b1, b2, a1, a2 = b
    w = 2 * math.pi * f / FS
    z1, z2 = complex(math.cos(w), -math.sin(w)), complex(math.cos(2 * w), -math.sin(2 * w))
    return 20 * math.log10(abs((b0 + b1 * z1 + b2 * z2) / (1 + a1 * z1 + a2 * z2)))


def peaking(f0, g):
    A = 10 ** (g / 40)
    w0 = 2 * math.pi * f0 / FS
    al, c = math.sin(w0) / (2 * Q), math.cos(w0)
    a0 = 1 + al / A
    return ((1 + al * A) / a0, -2 * c / a0, (1 - al * A) / a0, -2 * c / a0, (1 - al / A) / a0)


# response of each band at each integer gain on GRID, so fitting is lookups
BAND_DB = [[[biquad_db(peaking(fc, g), f) if g else 0.0 for f in GRID]
            for g in range(-MAX_DB, MAX_DB + 1)] for fc in BANDS]


def eq_curve(gains):
    return [sum(BAND_DB[b][g + MAX_DB][i] for b, g in enumerate(gains)) for i in range(len(GRID))]


def fit(target):
    """Integer band gains (+/-MAX_DB) minimising squared dB error on GRID."""
    def err(g):
        return sum((c - t) ** 2 for c, t in zip(eq_curve(g), target))
    g = [max(-MAX_DB, min(MAX_DB, round(t))) for t in
         (target[min(range(len(GRID)), key=lambda i: abs(GRID[i] - fc))] for fc in BANDS)]
    best = err(g)
    improved = True
    while improved:                                  # integer coordinate descent
        improved = False
        for i in range(len(BANDS)):
            for d in (-1, 1):
                h = list(g)
                h[i] = max(-MAX_DB, min(MAX_DB, h[i] + d))
                e = err(h)
                if e < best - 1e-9:
                    g, best, improved = h, e, True
    return g, math.sqrt(best / len(GRID))


def tone_records(path):
    prob, recs = eqtool.parse(open(path, 'rb').read())
    if prob:
        raise ValueError('%s: %s' % (path, prob))
    return [pl for t, pl in recs if t == 0x61]


def main(argv):
    if len(argv) != 4:
        sys.exit(__doc__)
    designer = ToneDesigner(argv[1])
    entries, worst = [], 0.0
    for path in sorted(glob.glob(os.path.join(argv[2], '*.bin'))):
        m = re.fullmatch(r'(\d+|HS)_(ON|OFF)\.bin', os.path.basename(path))
        if not m:
            continue                                 # legacy long names duplicate these
        cfg = HEADSET if m.group(1) == 'HS' else int(m.group(1))
        recs = tone_records(path)
        rows = []
        for vol in range(VOL_STEPS):
            slots = designer.design(recs, volume_step=max(vol, 1))
            curve = [sum(biquad_db(b, f) for b in slots.values()) for f in GRID]
            ref = sum(biquad_db(b, 1000.0) for b in slots.values())
            g, rms = fit([c - ref for c in curve])
            worst = max(worst, rms)
            rows.append(g)
        entries.append((cfg, m.group(2) == 'ON', rows))
        print('%-12s fitted' % os.path.basename(path), file=sys.stderr)
    with open(argv[3], 'w') as out:
        out.write('// SPDX-License-Identifier: MIT\n'
                  '/* Generated by tools/eq-voicing/gen_harley_eq.py - do not edit.\n'
                  ' * Harley tone stage (flat bass/treble, loudness by volume step, speed 0)\n'
                  ' * fitted to the 7-band EQ, relative to 1 kHz. Worst fit: %.2f dB RMS. */\n'
                  '#include "harley_eq_table.h"\n\n'
                  'const struct hbas_harley_voicing hbas_harley_voicing[] = {\n' % worst)
        for cfg, on, rows in entries:
            out.write('\t{ %d, %d, {\n' % (cfg, on))
            for g in rows:
                out.write('\t\t{ %s },\n' % ', '.join('%d' % x for x in g))
            out.write('\t} },\n')
        out.write('};\nconst unsigned hbas_harley_voicing_count = %d;\n' % len(entries))
    print('%d profiles, worst fit %.2f dB RMS' % (len(entries), worst), file=sys.stderr)


if __name__ == '__main__':
    main(sys.argv)
